apiVersion: v1
kind: Service
metadata:
  labels:
    app: openldap
  name: openldap
  namespace: openldap
spec:
  ports:
  - name: "http"
    port: 636
    targetPort: 636
  selector:
    app: openldap
  type: NodePort
